##端口
server:
  port: 8087
  context-path: /middleware

##日志存放
logging:
  path: /srv/dubbo/middleware/logs
  file: middleware
  level:
    org:
      springframework: info
    com:
      fasterxml:
        jackson: info
      hx:
        middleware: debug
##日期格式
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jmx:
    enabled: false
  ##数据源
  datasource:
    initialize: false
    url: jdbc:mysql://localhost:3306/middleware?serverTimezone=Asia/Shanghai
    username: root
    password: 8899
    driver-class-name: com.mysql.cj.jdbc.Driver

  ## redis配置
  redis:
    host: 182.92.5.36
    port: 6379
  ##rabbitmq配置
  rabbitmq:
    host: 182.92.5.36
    virtual-host: /
    port: 5672
    username: admin
    password: admin

#### mq的队列配置
mq:
  env: local
  basic:
    info:
      queue:
        name: ${mq.env}.middleware.mq.basic.info.queue
      exchange:
        name: ${mq.env}.middleware.mq.basic.info.exchange
      routing:
        key:
          name: ${mq.env}.middleware.mq.basic.info.routing.key
  object:
    info:
      queue:
        name: ${mq.env}.middleware.mq.object.info.queue
      exchange:
        name: ${mq.env}.middleware.mq.object.info.exchange
      routing:
        key:
          name: ${mq.env}.middleware.mq.object.info.routing.key
  fanout:
    queue:
      name:
        one: ${mq.env}.middleware.mq.fanout.one.queue
        two: ${mq.env}.middleware.mq.fanout.two.queue
    exchange:
      name: ${mq.env}.middleware.mq.fanout.exchange
  direct:
    queue:
      name:
        one: ${mq.env}.middleware.mq.direct.one.queue
        two: ${mq.env}.middleware.mq.direct.two.queue
    exchange:
      name: ${mq.env}.middleware.mq.direct.exchange
    routing:
      key:
        name:
          one: ${mq.env}.middleware.mq.direct.one.routing.key
          two: ${mq.env}.middleware.mq.direct.two.routing.key
  topic:
    queue:
      name:
        one: ${mq.env}.middleware.mq.topic.one.queue
        two: ${mq.env}.middleware.mq.topic.two.queue
    exchange:
      name: ${mq.env}.middleware.mq.topic.exchange
    routing:
      key:
        name:
          one: ${mq.env}.middleware.mq.topic.*.routing.key
          two: ${mq.env}.middleware.mq.topic.#.routing.key
  auto:
    knowledge:
      queue:
        name: ${mq.env}.middleware.mq.auto.knowledge.queue
      exchange:
        name: ${mq.env}.middleware.mq.auto.knowledge.exchange
      routing:
        key:
          name: ${mq.env}.middleware.mq.auto.knowledge.routing.key
  manual:
    knowledge:
      queue:
        name: ${mq.env}.middleware.mq.manual.knowledge.queue
      exchange:
        name: ${mq.env}.middleware.mq.manual.knowledge.exchange
      routing:
        key:
          name: ${mq.env}.middleware.mq.manual.knowledge.routing.key
  login:
    queue:
      name: ${mq.env}.middleware.mq.login.queue
    exchange:
      name: ${mq.env}.middleware.mq.login.exchange
    routing:
      key:
        name: ${mq.env}.middleware.mq.login.routing.key
  dead:
    queue:
      name: ${mq.env}.middleware.mq.dead.queue
    exchange:
      name: ${mq.env}.middleware.mq.dead.exchange
    routing:
      key:
        name: ${mq.env}.middleware.mq.dead.routing.key
  producer:
    basic:
      exchange:
        name: ${mq.env}.middleware.mq.producer.basic.exchange
      routing:
        key:
          name: ${mq.env}.middleware.mq.producer.basic.routing.key
  consumer:
    queue:
      name: ${mq.env}.middleware.mq.consumer.queue

  order:
    dead:
      queue:
        name: ${mq.env}.middleware.mq.order.dead.queue
      exchange:
        name: ${mq.env}.middleware.mq.order.dead.exchange
      routing:
        key:
          name: ${mq.env}.middleware.mq.order.dead.routing.key
    producer:
      basic:
        exchange:
          name: ${mq.env}.middleware.mq.order.producer.basic.exchange
        routing:
          key:
            name: ${mq.env}.middleware.mq.order.producer.basic.routing.key
    consumer:
      queue:
        name: ${mq.env}.middleware.mq.order.consumer.queue



## mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  check-config-location: true
  config-location: classpath:mybatis-config.xml

## zk配置
zk:
  host: 182.92.5.36:2181
  namespace: middleware_distributelock
