##端口
server:
  port: 8087
  context-path: /middleware

##日志存放
logging:
  path: /srv/dubbo/middleware/logs
  file: middleware
  level:
    org:
      springframework: info
    com:
      fasterxml:
        jackson: info
      hx:
        middleware: debug
##日期格式
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jmx:
    enabled: false
##数据源
  datasource:
    initialize: false
    url: jdbc:mysql://localhost:3306/middleware?serverTimezone=Asia/Shanghai
    username: root
    password: 8899
    driver-class-name: com.mysql.cj.jdbc.Driver

  ## redis配置
  redis:
    host: 182.92.5.36
    port: 6379

## mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  check-config-location: true
  config-location: classpath:mybatis-config.xml
